name: Build development container images

on:
  push:
    paths:
      - .github/workflows/docker-dev.yml
      - podman/dev/**
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to ghcr.io'
        required: false
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: alpine
            platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          - os: arch
            platforms: linux/amd64
          - os: debian
            platforms: linux/amd64,linux/arm64
          - os: fedora
            platforms: linux/amd64,linux/arm64
          - os: suse
            platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          - os: ubuntu
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_images == 'true') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: variables
        run: |
          echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
          echo "folder=./podman/dev" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ steps.variables.outputs.folder }}/${{ matrix.os }}
          file: ${{ steps.variables.outputs.folder }}/${{ matrix.os }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_images == 'true') }}
          tags: |
            ghcr.io/nathanchance/dev/${{ matrix.os }}:${{ steps.variables.outputs.date }}
            ghcr.io/nathanchance/dev/${{ matrix.os }}:latest
